FROM centos:centos6

# Install Tomcat
RUN wget http://www.us.apache.org/dist/tomcat/tomcat-7/v7.0.72/bin/apache-tomcat-7.0.72.tar.gz && \
    tar -xvf apache-tomcat-7.0.72.tar.gz && \
	mv apache-tomcat* /opt/tomcat 
# Setting up Working directory for tomcat
WORKDIR /opt/tomcat
# open default tomcat port
EXPOSE 8080
# start tomcat service
CMD /opt/tomcat/bin/startup.sh

# Install Python
RUN wget https://www.python.org/ftp/python/2.7.12/Python-2.7.12.tgz && \
	tar xzf Python-2.7.12.tgz && \
	cd Python-2.7.12 && \
	./configure && \
	make altinstall

# Install MongoDB
RUN yum -y update && yum install -y mongodb-org
# Expose port 27017
EXPOSE 27017
# Setting up Working directory for mongodb
WORKDIR /usr/bin/mongod